#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2019

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true

# fetch repository as zip archive. default is "false"
shallow_clone: true

# scripts that run after cloning repository
install:

build_script:
  - cmd: build.bat


#---------------------------------#
#       build configuration       #
#---------------------------------#

# to disable automatic builds
build:
#  off
  verbosity: normal
